<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>3c1a1d47-9007-45ef-b159-5272edeaea3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-comment-cookies-consent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wp-comment-cookies-consent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ea29b45-b4ac-43a0-bef0-cdb87b5ed0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-comment-cookies-consent</value>
      <webElementGuid>0f890439-614b-4e71-914c-ae79cc942733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wp-comment-cookies-consent</value>
      <webElementGuid>424c9b54-8cc5-4bc3-b140-6459ed4e2b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1ecd869f-f7de-40de-bcfb-87f8b52fc3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>023f66ef-63fc-47da-8f41-a32f5dfb8310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-comment-cookies-consent&quot;)</value>
      <webElementGuid>d2c04d46-da50-44b9-9ec6-a3dfe205e3d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-comment-cookies-consent']</value>
      <webElementGuid>65f56041-9b19-4bfe-9dd5-9e71d6650294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/p[5]/input</value>
      <webElementGuid>68707270-2a94-4448-999c-99cfd369a5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>dc4ae7e6-36a0-43a0-90e2-bbe165d129dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wp-comment-cookies-consent' and @name = 'wp-comment-cookies-consent' and @type = 'checkbox']</value>
      <webElementGuid>4addcc00-93e8-4a1c-b6e2-51191f3acbd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
