<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>duplicate</name>
   <tag></tag>
   <elementGuidId>d1686f7d-5354-4b9a-89a6-782468914eb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='error-page']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f773901e-dfb4-43ac-bf6d-7acad093ae44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Duplicate comment detected; it looks as though you’ve already said that!</value>
      <webElementGuid>f0aa309f-39d4-4e65-8ea5-cb41e705d32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-page&quot;)/div[@class=&quot;wp-die-message&quot;]/p[1]</value>
      <webElementGuid>579fe847-ba97-4acd-a94a-f99156ce3e8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='error-page']/div/p</value>
      <webElementGuid>7698dd40-b1df-4ce3-86df-6452ca3600a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='« Back'])[1]/preceding::p[1]</value>
      <webElementGuid>590e065e-9ef1-4e0f-82b9-8b9268b4fab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::p[2]</value>
      <webElementGuid>24532ad5-537a-4fdb-96ec-8b0ba1c123e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Duplicate comment detected; it looks as though you’ve already said that!']/parent::*</value>
      <webElementGuid>3c70d379-4016-4105-bab9-19717133a295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>f034ebed-8429-4e34-ab53-afc26cd9f581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Duplicate comment detected; it looks as though you’ve already said that!' or . = 'Duplicate comment detected; it looks as though you’ve already said that!')]</value>
      <webElementGuid>dfccbdd6-dda6-4e68-9050-a0676004c7a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
