<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_register</name>
   <tag></tag>
   <elementGuidId>67918c5a-8319-4bbf-80ec-b14089c54294</elementGuidId>
   <imagePath>Screenshots/Targets/page_register/btn_register.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-301']/div/figure/table/tbody/tr/td/div/div/form/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.um-center</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/page_register/btn_register.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3dbfe83-b3fa-4002-9fa3-9ffa6402ab71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-center</value>
      <webElementGuid>012b7c3e-c510-467b-8745-98c12089db6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-301&quot;)/div[@class=&quot;entry-content&quot;]/figure[@class=&quot;wp-block-table&quot;]/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;um um-register um-297 uimob500&quot;]/div[@class=&quot;um-form&quot;]/form[1]/div[@class=&quot;um-col-alt&quot;]/div[@class=&quot;um-center&quot;]</value>
      <webElementGuid>5fedbf1a-65a0-44bd-904d-b3cc0156749f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-301']/div/figure/table/tbody/tr/td/div/div/form/div[2]/div</value>
      <webElementGuid>130cb4e4-7449-41ac-8386-af8975794a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only fill in if you are not human'])[1]/following::div[2]</value>
      <webElementGuid>7a64c539-ee4e-4b63-8326-d9e417a493d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::div[4]</value>
      <webElementGuid>22f239cf-60a2-47d7-bcef-424bedf78a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/preceding::div[4]</value>
      <webElementGuid>c7aa51ed-b72a-4480-b10f-78d0313bd27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>5087e253-388d-4146-998e-093222972bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
